coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5
        base: auto
        informational: true
    patch:
      default:
        target: auto
        threshold: 5
        base: auto
